In [1]:
import pandas as pd 
import json
import numpy as np

In [2]:
df = pd.read_csv("atach50/df50.csv")

In [3]:
df.columns

Index(['treatment', 'age', 'mRS score after 90 days',
       'mRS score after 30 days', 'adverse events', 'ICH volume',
       'ICH Location', 'IVH volume', 'GCS score', 'NIHSS score',
       'Systolic blood pressure', 'Diastolic Blood Pressure', 'Hypertension',
       'Hyperlipidemia', 'Type I Diabetes', 'Type II Diabetes',
       'Congestive heart failure', 'Atrial Fibrillation', 'PTCA',
       'Peripheral Vascular Disease', 'Myocardial fraction', 'Anti-diabetic',
       'Antihypertensives', 'White blood count', 'Hemoglobin', 'Hematocrit',
       'Platelet count', 'APTT', 'INR', 'Glucose', 'Sodium', 'Potassium',
       'Chloride', 'CD', 'Blood urea nitrogen', 'Creatinine', 'race', 'sex',
       'ethnicity'],
      dtype='object')

In [4]:
df.head()

,treatment,age,mRS score after 90 days,mRS score after 30 days,adverse events,ICH volume,ICH Location,IVH volume,GCS score,NIHSS score,...,Glucose,Sodium,Potassium,Chloride,CD,Blood urea nitrogen,Creatinine,race,sex,ethnicity
0,1,68.0,4.0,4.0,0,14.91285,R Basal Ganglia,0.0,15.0,11.0,...,108.0,135.0,3.9,100.4,26.3,13.5,0.50,Asian,Female,Non-Hispanic
1,0,65.0,2.0,3.0,0,14.91115,R Basal Ganglia,0.0,14.0,11.0,...,109.0,144.0,3.7,108.0,27.0,14.0,0.83,Asian,Male,Non-Hispanic
2,0,41.0,1.0,2.0,0,4.00650,L Thalamus,0.0,15.0,6.0,...,178.0,135.0,3.4,103.0,21.0,13.0,0.71,Asian,Female,Non-Hispanic
3,0,60.0,3.0,3.0,0,3.06625,L Basal Ganglia,0.0,15.0,9.0,...,117.0,142.0,3.5,105.0,25.0,9.9,0.72,Asian,Male,Non-Hispanic
4,1,55.0,2.0,3.0,0,3.38792,R Thalamus,0.0,15.0,12.0,...,149.0,141.0,3.8,110.0,24.2,13.3,0.90,Asian,Male,Non-Hispanic

In [5]:
x_cols = ['treatment', 'age', 'ICH volume',
       'ICH Location', 'IVH volume', 'GCS score', 'NIHSS score',
       'Systolic blood pressure',
       'Diastolic Blood Pressure',
       'Hypertension', 'Hyperlipidemia',
       'Type I Diabetes', 'Type II Diabetes',
       'Congestive heart failure', 'Atrial Fibrillation',
       'PTCA',
       'Peripheral Vascular Disease',
       'Myocardial fraction', 'Anti-diabetic',
       'Antihypertensives', 'White blood count', 'Hemoglobin',
       'Hematocrit', 'Platelet count', 'APTT', 'INR', 'Glucose', 'Sodium',
       'Potassium', 'Chloride', 'CD', 'Blood urea nitrogen', 'Creatinine',
       'race', 'sex', 'ethnicity']
y_col = 'mRS score after 30 days'

cols = x_cols + [y_col]

In [6]:
df = df[cols].copy()
df.to_csv("atach50/df50.csv", index=False)

In [8]:
df50_test = pd.read_csv("atach50/df50_test.csv")
df50_test = df50_test[cols]
df50_test.head()

,treatment,age,ICH volume,ICH Location,IVH volume,GCS score,NIHSS score,Systolic blood pressure,Diastolic Blood Pressure,Hypertension,...,Sodium,Potassium,Chloride,CD,Blood urea nitrogen,Creatinine,race,sex,ethnicity,mRS score after 30 days
0,1,58.0,11.00301,R Basal Ganglia,0.00000,15.0,14.0,181.0,85.0,1.0,...,141.0,3.4,106.0,27.2,20.00,0.79,Asian,Female,Non-Hispanic,3.0
1,1,39.0,21.55289,L Thalamus,0.00391,14.0,19.0,143.0,67.0,1.0,...,142.0,3.9,106.0,26.0,33.00,2.78,White,Male,Hispanic,4.0
2,1,62.0,5.60495,L Basal Ganglia,0.00000,15.0,10.0,145.0,68.0,1.0,...,142.0,4.0,106.0,25.0,16.00,0.70,White,Female,Hispanic,5.0
3,0,51.0,36.85009,R Basal Ganglia,0.00000,14.0,12.0,201.0,138.0,0.0,...,147.0,4.1,106.9,24.1,14.85,0.80,Asian,Male,Non-Hispanic,3.0
4,1,48.0,26.55593,L Basal Ganglia,0.00000,13.0,18.0,183.0,88.0,1.0,...,138.0,3.4,107.0,23.3,11.80,0.90,Asian,Male,Non-Hispanic,1.0

In [9]:
df50_test.to_csv("atach50/df50_test.csv", index=False)

In [10]:
df25 = pd.read_csv("atach25/df25.csv")
df25 = df25[cols]
df25.to_csv("atach25/df25.csv", index=False)

In [11]:
df25_test = pd.read_csv("atach25/df25_test.csv")
df25_test = df25_test[cols]
df25_test.to_csv("atach25/df25_test.csv", index=False)

# ERICH

In [12]:
df = pd.read_csv("erich25/df25.csv")

In [13]:
df.head()

,mRS score after 90 days,sex,age,race,ICH volume,IVH volume,ICH location,GCS score,Systolic blood pressure,Diastolic blood pressure,...,PTCA,Myocardial infraction,anti-diabetic,Anti-hypertensives,White blood cell count,Hemoglobin,Platelet count,APTT,INR,Glucose
0,4.0,1,50.0,Hispanic,7.648,0.000,L Putaminal,12.0,179.0,105.0,...,0,0,0,0,9.0,16.8,194.0,29.5,0.87,122.0
1,4.0,0,78.0,White,3.184,5.626,L Caudate Nucleus,15.0,129.0,65.0,...,0,0,0,0,12.8,14.2,196.0,27.0,1.00,113.0
2,4.0,1,62.0,Black,38.715,18.533,R Putaminal,15.0,234.0,138.0,...,0,0,0,0,9.8,14.8,147.0,25.0,1.10,108.0
3,3.0,0,75.0,Hispanic,3.286,0.000,R Frontal,10.0,120.0,65.0,...,0,0,1,1,6.5,12.5,173.0,42.7,3.40,184.0
4,1.0,1,43.0,Black,12.234,0.000,L Putaminal,7.0,162.0,130.0,...,0,0,0,0,5.8,16.3,193.0,29.5,0.90,99.0

In [14]:
x_cols = ['sex', 'age', 'race', 'ICH volume', 'IVH volume',
       'ICH location', 'GCS score', 'Systolic blood pressure',
       'Diastolic blood pressure', 'Hypertension', 'Hyperlipidemia',
       'Type 2 diabetes', 'Type 1 diabetes', 'Atrial Fibrillation',
       'Congestive Heart Failure', 'Vascular disease', 'Cocaine use', 'Smoke',
       'PTCA', 'Myocardial infraction', 'anti-diabetic', 'Anti-hypertensives',
       'White blood cell count', 'Hemoglobin', 'Platelet count', 'APTT', 'INR',
       'Glucose']
y_col = 'mRS score after 90 days'
cols = x_cols + [y_col]

In [15]:
df = df[cols]

In [16]:
df.to_csv("erich25/df25.csv", index=False)

In [17]:
df25_test = pd.read_csv("erich25/df25_test.csv")

In [18]:
df25_test = df25_test[cols]
df25_test.to_csv("erich25/df25_test.csv", index=False)

In [20]:
df50 = pd.read_csv("erich50/df50.csv")
df50 = df50[cols]
df50.to_csv("erich50/df50.csv", index=False)

In [22]:
df50_test = pd.read_csv("erich50/df50_test.csv")
df50_test = df50_test[cols]
df50_test.to_csv("erich50/df50_test.csv", index=False)